use_frameworks!
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

platform :ios, '9.0'

target 'MJBaseUtils_Example' do
  pod 'MJBaseUtils', :path => '../'

  target 'MJBaseUtils_Tests' do
    inherit! :search_paths

  end
end
